input.onButtonPressed(Button.A, function () {
    basic.showIcon(IconNames.EigthNote)
    music.playTone(262, music.beat(BeatFraction.Breve))
    basic.showIcon(IconNames.Diamond)
    music.playTone(294, music.beat(BeatFraction.Double))
    basic.showIcon(IconNames.Scissors)
    music.playTone(330, music.beat(BeatFraction.Double))
    basic.showIcon(IconNames.Heart)
    music.playTone(262, music.beat(BeatFraction.Breve))
    basic.showIcon(IconNames.TShirt)
    music.playTone(294, music.beat(BeatFraction.Double))
    basic.showIcon(IconNames.Sword)
    music.playTone(330, music.beat(BeatFraction.Double))
    basic.showIcon(IconNames.Rollerskate)
    music.playTone(262, music.beat(BeatFraction.Breve))
    if (true) {
        basic.showIcon(IconNames.Yes)
        basic.showString(" finis")
        basic.showIcon(IconNames.Happy)
        music.playMelody("D F G A C5 F E D ", 120)
    }
})
input.onButtonPressed(Button.B, function () {
    basic.showIcon(IconNames.Skull)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D E C5 A G C B ", 385)
    music.playMelody("F D E C5 A G C B ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
    music.playMelody("F D C5 C A G B E ", 385)
    music.playMelody("F D C5 C A G B E ", 385)
    music.playMelody("F D C5 C A B E C ", 385)
})
basic.forever(function () {
	
})
